Repository rwth-acis/REST-OCD-Services, pull requests merged in 2023-03, with the labels that each got.

#109 update wiki
  README.md
  docs/pages/index.md
  docs/pages/wiki/build-process.md
  docs/pages/wiki/database-configuration.md
  docs/pages/wiki/integration.md
  docs/pages/wiki/project-structure.md
  docs/pages/wiki/running.md
  docs/pages/wiki/service-deployment.md
  docs/pages/wiki/user-management-and-authentication.md
Labels: documentation

#110 fix storing OCDA parameters in the db
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/ServiceClass.java
Labels: bug, enhancement

#112 Fix removeMultiEdges method
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/graphs/GraphProcessor.java
Labels: bug

#116 remove unnecesasry code remaining from JPA
  etc/i5.las2peer.services.ocd.ServiceClass.properties
  etc/userLimitInformation.json
  ocd/.gitignore
  ocd/eclipselink/serviceCreateDDL.jdbc
  rest_ocd_services/src/main/java/META-INF/persistence.xml
  rest_ocd_services/src/main/java/META-INF/testing/persistence.xml
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/ServiceClass.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/centrality/data/CentralityCreationLog.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/centrality/data/CentralityMap.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/mapping/CoverSimulationGroupMapping.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/mapping/CoverSimulationSeriesMapping.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/mapping/MappingAbstract.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/mapping/SimulationGroupSetMapping.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/mapping/SimulationSeriesSetMapping.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/mapping/correlation/Correlation.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/mapping/correlation/Inference.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/simulation/AgentData.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/simulation/Evaluation.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/simulation/GroupParameters.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/simulation/SimulationAbstract.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/simulation/SimulationDataset.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/simulation/SimulationSeries.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/simulation/SimulationSeriesGroup.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/cooperation/data/simulation/SimulationSeriesParameters.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/graphs/Community.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/graphs/Cover.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/graphs/CoverCreationLog.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/graphs/CustomEdge.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/graphs/CustomGraph.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/graphs/CustomNode.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/graphs/GraphCreationLog.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/metrics/OcdMetricLog.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/AlgorithmRunnable.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/CentralityAlgorithmRunnable.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/CentralitySimulationRunnable.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/Database.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/GroundTruthBenchmarkRunnable.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/InactivityData.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/InactivityHandler.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/InvocationHandler.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/KnowledgeDrivenMeasureRunnable.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/StatisticalMeasureRunnable.java
  rest_ocd_services/src/main/java/i5/las2peer/services/ocd/utils/ThreadHandler.java
  rest_ocd_services/src/test/java/i5/las2peer/services/ocd/Playground.java
  rest_ocd_services/src/test/java/i5/las2peer/services/ocd/ServiceTest.java
  rest_ocd_services/src/test/java/i5/las2peer/services/ocd/graphs/CustomGraphDatabaseTest.java
  rest_ocd_services/src/test/java/i5/las2peer/services/ocd/utils/InvocationHandlerTest.java
Labels: enhancement
